/**
 * Complete country-level regulatory data for all key cannabis import markets.
 * Separated from regulatory-requirements.ts for maintainability.
 */
import type { CountryRegulation } from "./regulatory-requirements";

export const KEY_MARKETS: CountryRegulation[] = [
  // ═══════════════════════════════════════════════════
  //  EUROPE
  // ═══════════════════════════════════════════════════
  {
    code: "DE", name_de: "Deutschland", name_en: "Germany", flag: "🇩🇪", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "BfArM-reguliert. EU-GMP Pflicht. Größter europäischer Importmarkt. INCB-Kontingent beachten.",
    regulatory_body: "BfArM", import_license_required: true,
    special_requirements: ["EU-GMP-Zertifikat (nicht nur GMP)", "BfArM Import-Genehmigung", "INCB-Kontingent beim Bundesopiumamt", "Qualified Person (QP) Freigabe in EU"],
  },
  {
    code: "UK", name_de: "Vereinigtes Königreich", name_en: "United Kingdom", flag: "🇬🇧", region: "europe",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "product_specification"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "MHRA-reguliert. Schedule 2 Controlled Drug. Specialist-Verschreibung. Home Office Import-Lizenz.",
    regulatory_body: "MHRA / Home Office", import_license_required: true,
    special_requirements: ["Home Office Controlled Drug Import Licence", "MHRA-registrierter Importeur erforderlich", "GMP-Compliance nach UK (ex-EU) Standard", "Specialist Doctor Prescription (kein GP)", "Batch-spezifische Qualitätsfreigabe (QP Release)"],
  },
  {
    code: "IT", name_de: "Italien", name_en: "Italy", flag: "🇮🇹", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "product_specification"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "AIFA-reguliert. Medizinisches Cannabis seit 2007 erlaubt. Import über autorisierte Großhändler.",
    regulatory_body: "AIFA (Agenzia Italiana del Farmaco)", import_license_required: true,
    special_requirements: ["AIFA-Importgenehmigung erforderlich", "Verschreibung durch Facharzt (Ricetta Non Ripetibile)", "EU-GMP-Zertifikat zwingend", "Ministerium für Gesundheit muss jede Importcharge genehmigen", "THC-Gehalt auf Etikett in mg/g angeben"],
  },
  {
    code: "PL", name_de: "Polen", name_en: "Poland", flag: "🇵🇱", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "GIF reguliert. Medizinisches Cannabis seit 2017 legalisiert. Schnell wachsender Markt.",
    regulatory_body: "GIF (Główny Inspektor Farmaceutyczny)", import_license_required: true,
    special_requirements: ["GIF-Importgenehmigung je Charge", "EU-GMP-Zertifikat erforderlich", "Pharmazeutische Großhandelserlaubnis", "Rezeptpflicht über spezialisierten Arzt"],
  },
  {
    code: "CZ", name_de: "Tschechien", name_en: "Czech Republic", flag: "🇨🇿", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "pesticide_report"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "SÚKL-reguliert. Medizinisches Cannabis seit 2013 legal.",
    regulatory_body: "SÚKL", import_license_required: true,
    special_requirements: ["SÚKL-Lizenz für Import und Vertrieb", "EU-GMP-Zertifikat zwingend", "Elektronisches Rezept (ePreskripce)", "Quarantäne-Prüfung bei Einfuhr durch SAKL", "Pestizid-Analyse nach EU-Pharmastandards"],
  },
  {
    code: "FR", name_de: "Frankreich", name_en: "France", flag: "🇫🇷", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "ANSM-reguliert. Experimentelles Programm für medizinisches Cannabis seit 2021.",
    regulatory_body: "ANSM", import_license_required: true,
    special_requirements: ["ANSM-Sondergenehmigung (ATU nominative)", "EU-GMP-Zertifikat zwingend", "Stabilitätsstudien nach ICH-Richtlinien", "Nur durch zugelassene Apotheken abzugeben", "ANSM-konforme Verpackung und Kennzeichnung (Französisch)"],
  },
  {
    code: "ES", name_de: "Spanien", name_en: "Spain", flag: "🇪🇸", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "AEMPS-reguliert. Import hauptsächlich für klinische Studien und Magistralrezepturen.",
    regulatory_body: "AEMPS", import_license_required: true,
    special_requirements: ["AEMPS-Importgenehmigung", "EU-GMP-Zertifikat erforderlich", "Nur für Magistralrezepturen oder klinische Studien", "Autonome Gemeinschaften haben unterschiedliche Regelungen"],
  },
  {
    code: "PT", name_de: "Portugal", name_en: "Portugal", flag: "🇵🇹", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "EU-GACP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "gacp_cert"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Infarmed-reguliert. Einer der führenden EU-Produzenten.",
    regulatory_body: "Infarmed", import_license_required: true,
    special_requirements: ["Infarmed-Lizenz für Herstellung/Import", "EU-GMP oder EU-GACP je nach Verarbeitungsstufe", "INCB-Kontingent erforderlich", "QP-Freigabe für jede Charge"],
  },
  {
    code: "NL", name_de: "Niederlande", name_en: "Netherlands", flag: "🇳🇱", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "BMC reguliert. Pionier im medizinischen Cannabis. Strenge Qualitätsstandards.",
    regulatory_body: "BMC / CIBG", import_license_required: true,
    special_requirements: ["BMC-Opiumgesetz-Lizenz (Opiumwet)", "EU-GMP-Zertifikat zwingend", "Nur über autorisierte Apotheken", "Niederländische Pharmakovigilanz-Meldepflicht"],
  },
  {
    code: "CH", name_de: "Schweiz", name_en: "Switzerland", flag: "🇨🇭", region: "europe",
    max_thc: 1.0, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Swissmedic/BAG-reguliert. THC-Grenze für CBD-Produkte: 1%.",
    regulatory_body: "Swissmedic / BAG", import_license_required: true,
    special_requirements: ["BAG-Sonderbewilligung (Ausnahmebewilligung BetmG)", "Swissmedic GMP-Inspektion oder Anerkennung", "THC ≤1% für frei verkäufliche CBD-Produkte", "Stabilitätsstudien nach ICH-Richtlinien", "INCB-Kontingent beim BAG"],
  },
  {
    code: "AT", name_de: "Österreich", name_en: "Austria", flag: "🇦🇹", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "AGES/BASG-reguliert. Suchtmittelgesetz. EU-GMP Pflicht.",
    regulatory_body: "AGES / BASG", import_license_required: true,
    special_requirements: ["BASG-Importgenehmigung", "EU-GMP-Zertifikat zwingend", "Suchtgiftrezept (gelbes Rezept) erforderlich", "Magistralrezepturen in Apotheken"],
  },
  {
    code: "DK", name_de: "Dänemark", name_en: "Denmark", flag: "🇩🇰", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "product_specification"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "DKMA reguliert. Pilotprogramm für medizinisches Cannabis seit 2018.",
    regulatory_body: "DKMA (Lægemiddelstyrelsen)", import_license_required: true,
    special_requirements: ["DKMA Cannabis-Pilotprogramm-Lizenz", "EU-GMP-Zertifikat zwingend", "Ärztliche Verschreibung erforderlich", "Dänische Produktkennzeichnung"],
  },
  {
    code: "IE", name_de: "Irland", name_en: "Ireland", flag: "🇮🇪", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "HPRA-reguliert. Medical Cannabis Access Programme (MCAP) seit 2019.",
    regulatory_body: "HPRA", import_license_required: true,
    special_requirements: ["HPRA-Importlizenz (Misuse of Drugs Regulations)", "Nur MCAP-zugelassene Indikationen", "EU-GMP-Zertifikat zwingend", "Consultant-Verschreibung (kein GP)"],
  },
  {
    code: "GR", name_de: "Griechenland", name_en: "Greece", flag: "🇬🇷", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "EU-GACP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "gacp_cert"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "EOF reguliert. Seit 2018 Anbau und Export erlaubt.",
    regulatory_body: "EOF", import_license_required: true,
    special_requirements: ["EOF-Lizenz für pharmazeutische Cannabis-Produkte", "EU-GMP oder EU-GACP je nach Verarbeitungsstufe", "INCB-Kontingent über griechisches Gesundheitsministerium"],
  },
  {
    code: "MT", name_de: "Malta", name_en: "Malta", flag: "🇲🇹", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "EU-GACP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Superintendent of Public Health reguliert. Erstes EU-Land mit Freizeitlegalisierung (2021).",
    regulatory_body: "Superintendent of Public Health", import_license_required: true,
    special_requirements: ["Authority for the Responsible Use of Cannabis (ARUC) Lizenz", "EU-GMP-Zertifikat für medizinische Produkte", "Separate Lizenzierung für Freizeit- vs. Medizinalmarkt"],
  },
  {
    code: "LU", name_de: "Luxemburg", name_en: "Luxembourg", flag: "🇱🇺", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Ministère de la Santé reguliert. Medizinisches Cannabis seit 2018.",
    regulatory_body: "Ministère de la Santé", import_license_required: true,
    special_requirements: ["Genehmigung des Gesundheitsministeriums", "EU-GMP-Zertifikat zwingend", "Ärztliche Verschreibung über spezialisierten Arzt"],
  },
  {
    code: "CY", name_de: "Zypern", name_en: "Cyprus", flag: "🇨🇾", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Pharmaceutical Services reguliert. Medizinisches Cannabis seit 2019 erlaubt.",
    regulatory_body: "Pharmaceutical Services", import_license_required: true,
    special_requirements: ["Pharmazeutische Import-Lizenz", "EU-GMP-Zertifikat erforderlich", "Fachärztliche Verschreibung"],
  },
  {
    code: "NO", name_de: "Norwegen", name_en: "Norway", flag: "🇳🇴", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "product_specification"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "NoMA reguliert. Kein EU-Mitglied, aber EWR. Sehr restriktive Verschreibungspraxis.",
    regulatory_body: "NoMA (Statens legemiddelverk)", import_license_required: true,
    special_requirements: ["NoMA-Importgenehmigung (Spesiell godkjenningsfritak)", "EU-GMP oder PIC/S-konformes GMP-Zertifikat", "Nur als individueller Therapieversuch verschreibbar", "Norwegische Sprache auf Verpackung empfohlen"],
  },
  {
    code: "HR", name_de: "Kroatien", name_en: "Croatia", flag: "🇭🇷", region: "europe",
    max_thc: 100, min_certifications: ["EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "HALMED-reguliert. Medizinisches Cannabis seit 2015 legalisiert.",
    regulatory_body: "HALMED", import_license_required: true,
    special_requirements: ["HALMED-Importgenehmigung", "EU-GMP-Zertifikat zwingend", "Verschreibung durch Facharzt"],
  },

  // ═══════════════════════════════════════════════════
  //  ASIA-PACIFIC
  // ═══════════════════════════════════════════════════
  {
    code: "AU", name_de: "Australien", name_en: "Australia", flag: "🇦🇺", region: "asia_pacific",
    max_thc: 100, min_certifications: ["EU-GMP", "GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study", "product_specification"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "TGA reguliert. SAS/AP Scheme. PIC/S-GMP oder EU-GMP akzeptiert.",
    regulatory_body: "TGA (Therapeutic Goods Administration)", import_license_required: true,
    special_requirements: ["TGA SAS Category B oder Authorised Prescriber Pathway", "Office of Drug Control (ODC) Import Licence", "PIC/S-konformer GMP-Standard (EU-GMP wird akzeptiert)", "Stabilitätsstudien nach ICH-Richtlinien", "TGA-konforme Verpackung und Kennzeichnung", "Poisons Standard Schedule 8 (THC) oder Schedule 4 (CBD ≤150mg)"],
  },
  {
    code: "TH", name_de: "Thailand", name_en: "Thailand", flag: "🇹🇭", region: "asia_pacific",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "pesticide_report"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Thai FDA reguliert. Cannabis 2022 entkriminalisiert, neue Regulierung in Vorbereitung.",
    regulatory_body: "Thai FDA", import_license_required: true,
    special_requirements: ["Thai FDA Cannabis-Importlizenz", "Thai GMP oder PIC/S-konformes GMP-Zertifikat", "Pestizid-Analyse nach Thai-FDA-Standards", "Kennzeichnung in Thai und Englisch", "Registrierung beim Ministry of Public Health"],
  },
  {
    code: "IL", name_de: "Israel", name_en: "Israel", flag: "🇮🇱", region: "asia_pacific",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study", "pesticide_report"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "IMCA reguliert. Einer der fortschrittlichsten Märkte weltweit. ~120.000 Patienten.",
    regulatory_body: "IMCA (Israel Medical Cannabis Agency)", import_license_required: true,
    special_requirements: ["IMCA-Importlizenz erforderlich", "IMC-GMP oder EU-GMP-Standard", "Stabilitätsstudien nach ICH", "Pestizid-Analyse nach israelischen Standards (sehr streng)", "Kennzeichnung auf Hebräisch", "Patienten-Tracking über IMCA-System"],
  },
  {
    code: "KR", name_de: "Südkorea", name_en: "South Korea", flag: "🇰🇷", region: "asia_pacific",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study", "product_specification"],
    category_restrictions: [], cbd_restricted: true,
    notes_de: "MFDS reguliert. Seit 2018 medizinisches Cannabis in sehr eingeschränktem Umfang erlaubt.",
    regulatory_body: "MFDS (Ministry of Food and Drug Safety)", import_license_required: true,
    special_requirements: ["MFDS Orphan Drug Designation erforderlich", "Korea GMP oder EU-GMP-Zertifikat", "Individuelle Importgenehmigung pro Patient", "Narcotics Control Act – strenge Mengenkontrolle", "Koreanische Kennzeichnung erforderlich"],
  },
  {
    code: "JP", name_de: "Japan", name_en: "Japan", flag: "🇯🇵", region: "asia_pacific",
    max_thc: 0.0, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study", "product_specification"],
    category_restrictions: ["Extract", "Oil", "Isolate"], cbd_restricted: false,
    notes_de: "MHLW reguliert. THC strikt verboten (0%). Nur CBD-Produkte ohne THC-Nachweis erlaubt.",
    regulatory_body: "MHLW (Ministry of Health, Labour and Welfare)", import_license_required: true,
    special_requirements: ["THC muss unter Nachweisgrenze sein (0.0%)", "Nur Extrakte/Öle aus Samen oder reifen Stängeln", "MHLW-Importgenehmigung erforderlich", "Japan GMP (PMDA) oder EU-GMP-Standard", "Japanische Kennzeichnung (JIS-konform)", "Keine Blütenprodukte erlaubt"],
  },
  {
    code: "NZ", name_de: "Neuseeland", name_en: "New Zealand", flag: "🇳🇿", region: "asia_pacific",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study", "product_specification"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Medsafe reguliert. Medicinal Cannabis Scheme seit 2020.",
    regulatory_body: "Medsafe", import_license_required: true,
    special_requirements: ["Medsafe Cannabis Licence", "Minimum Quality Standard (MQS) Compliance", "GMP-Zertifikat (PIC/S oder EU-GMP)", "Stabilitätsstudien nach ICH", "Verordnung durch registrierten Arzt"],
  },

  // ═══════════════════════════════════════════════════
  //  AMERICAS
  // ═══════════════════════════════════════════════════
  {
    code: "US", name_de: "USA", name_en: "United States", flag: "🇺🇸", region: "americas",
    max_thc: 0.3, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "fda_registration", "import_permit", "stability_study"],
    category_restrictions: [], cbd_restricted: true,
    notes_de: "FDA/DEA-reguliert. Farm Bill: Hanf ≤0.3% THC. DEA Import-Lizenz für medizinisches Cannabis.",
    regulatory_body: "FDA / DEA", import_license_required: true,
    special_requirements: ["DEA-Importlizenz für THC > 0.3%", "FDA-Registrierung für Lebensmittel/Nahrungsergänzungsmittel", "State-by-State Regulierung beachten", "cGMP (21 CFR Part 211) für pharmazeutische Produkte", "COA mit akkreditiertem US-Labor empfohlen"],
  },
  {
    code: "CA", name_de: "Kanada", name_en: "Canada", flag: "🇨🇦", region: "americas",
    max_thc: 100, min_certifications: ["GACP", "EU-GACP", "GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "pesticide_report"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "Health Canada / Cannabis Act (2018). Strenge Pestizid-Grenzwerte.",
    regulatory_body: "Health Canada", import_license_required: true,
    special_requirements: ["Health Canada Cannabis Licence", "Import Permit für jede Lieferung erforderlich", "Pestizid-Analyse nach Health Canada Standards (>96 Substanzen)", "Schwermetall-Analyse (Pb, As, Cd, Hg)", "Mikrobiologische Prüfung nach USP-Standards", "Cannabis Tracking System (CTLS) Registrierung"],
  },
  {
    code: "BR", name_de: "Brasilien", name_en: "Brazil", flag: "🇧🇷", region: "americas",
    max_thc: 0.2, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study", "product_specification"],
    category_restrictions: ["Oil", "Extract"], cbd_restricted: false,
    notes_de: "ANVISA-reguliert. RDC 660/2022 erlaubt Import von Cannabis-Produkten. Nur Öle und Extrakte.",
    regulatory_body: "ANVISA", import_license_required: true,
    special_requirements: ["ANVISA-Registrierung oder Sondergenehmigung", "Brasilianische GMP-Inspektion oder MRA-Anerkennung", "Stabilitätsstudien unter tropischen Bedingungen (Zone IVb)", "Portugiesische Kennzeichnung erforderlich", "Nur Öle/Extrakte – keine Blüten erlaubt", "THC ≤0.2% für nicht-verschreibungspflichtige Produkte"],
  },
  {
    code: "CO", name_de: "Kolumbien", name_en: "Colombia", flag: "🇨🇴", region: "americas",
    max_thc: 100, min_certifications: ["GACP", "EU-GACP", "GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "gacp_cert"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "INVIMA/MinJusticia reguliert. Primär Exportland, aber auch Import möglich.",
    regulatory_body: "INVIMA / MinJusticia", import_license_required: true,
    special_requirements: ["INVIMA-Registrierung für pharmazeutische Produkte", "MinJusticia-Lizenz für psychoaktives Cannabis", "ICA-Phytosanitärzertifikat", "Spanische Kennzeichnung erforderlich"],
  },
  {
    code: "UY", name_de: "Uruguay", name_en: "Uruguay", flag: "🇺🇾", region: "americas",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "IRCCA reguliert. Erstes Land mit vollständiger Legalisierung (2013).",
    regulatory_body: "IRCCA", import_license_required: true,
    special_requirements: ["IRCCA-Lizenz für Import", "GMP-Zertifikat erforderlich", "Registrierung beim MSP (Ministerio de Salud Pública)", "Spanische Kennzeichnung"],
  },

  // ═══════════════════════════════════════════════════
  //  AFRICA
  // ═══════════════════════════════════════════════════
  {
    code: "ZA", name_de: "Südafrika", name_en: "South Africa", flag: "🇿🇦", region: "africa",
    max_thc: 100, min_certifications: ["GMP", "EU-GMP"],
    required_documents: ["coa", "gmp_cert", "import_permit", "stability_study"],
    category_restrictions: [], cbd_restricted: false,
    notes_de: "SAHPRA reguliert. Cannabis for Private Purposes Act. Aufstrebender Markt.",
    regulatory_body: "SAHPRA", import_license_required: true,
    special_requirements: ["SAHPRA Section 21 Genehmigung", "GMP-Zertifikat (PIC/S oder EU-GMP)", "Medicines Control Council Import Permit", "Stabilitätsstudien unter klimatischen Zone II/IVa", "Englische Kennzeichnung"],
  },
];
